Add force_refresh option to ObjectFormWidget
locomotivemtl/charcoal-admin pull request #52
Opened 2021-09-22 14:23 UTC by MouseEatsCat

This option will force the form widget to refresh the page after update (when set to: true).
Example:
```JSON
"admin.edit": {
    "widgets": {
        "form": {
            "type": "charcoal/admin/widget/object-form",
            "form_ident": "default",
            "obj_type": "charcoal/admin/object/object-name",
            "group_display_mode": "tab",
            "force_refresh": true
        }
    }
}
```

2021-09-22 14:48 UTC, mcaskill requested changes

2021-09-22 14:48 UTC, mcaskill commented on src/Charcoal/Admin/Widget/ObjectFormWidget.php
> +            'force_refresh'       => $this->forceRefresh()
Fix alignment of `key => value` assignment operators and add trailing comma for multi-line array declarations.

```suggestion
            'allow_reload'       => $this->allowReload(),
            'force_refresh'      => $this->forceRefresh(),
```

2021-09-22 14:48 UTC, mcaskill commented on assets/src/scripts/charcoal/admin/widget/form.js
> +    this.force_refresh     = opts.data.force_refresh;
I think we should rename this property to `force_page_refresh` to distinguish from `allow_reload` which should have been named `force_widget_reload` (to be resolved in a future changeset).

```suggestion
    this.force_page_refresh = opts.data.force_page_refresh;
```

Don't forget to fix alignment of `=` assignment operators.

2021-09-22 14:48 UTC, mcaskill commented on assets/src/scripts/charcoal/admin/widget/form.js
> +
If the response has feedback (`response.feedbacks`), the force refresh should occur after a confirmation alert, similar to `response.next_url` above.

```suggestion
        if (this.force_refresh) {
			if (response.feedbacks) {
				// @todo "dynamise" the label
				Charcoal.Admin.feedback().add_action({
					label:    commonL10n.continue,
					callback: function () {
						window.location.reload();
					}
				});
			} else {
                window.location.reload();
            }
        }

```

Also, `window.location.reload()` seems like the better option for reloading the page.

2021-09-22 14:48 UTC, mcaskill commented on assets/src/scripts/charcoal/admin/widget/form.js
> +    this.force_refresh    = opts.data.force_refresh;
I think this property should be called `force_page_reload` to clarify its purpose, match the [`Location.reload()` API](https://developer.mozilla.org/en-US/docs/Web/API/Location/reload), and distinguish itself from `allow_reload`, which should have been called `force_widget_reload`.

```suggestion
    this.force_page_reload = opts.data.force_page_reload;
```

2021-09-22 14:50 UTC, mcaskill commented on src/Charcoal/Admin/Widget/ObjectFormWidget.php
> +            'force_refresh'      => $this->forceRefresh()
Add trailing comma for multi-line array declarations.

```suggestion
            'force_refresh'      => $this->forceRefresh(),
```

2021-09-23 17:33 UTC, MouseEatsCat commented
@mcaskill My logic is that the force refresh should behave similarly to the `this.is_new_object` when it redirects you to the edit page when you hit save (on a "create" form).

2021-09-23 17:34 UTC, mcaskill commented
> @mcaskill My logic is that the force refresh should behave similarly to the `this.is_new_object` when it redirects you to the edit page when you hit save (on a "create" form).

I completely agree.

2021-09-23 17:49 UTC, mcaskill approved these changes

2021-09-29 15:44 UTC, merged