1st version of new group_display_mode for quick-form
locomotivemtl/charcoal-admin pull request #63
Opened 2022-06-02 15:01 UTC by veve40

2022-06-02 15:10 UTC, JoelAlphonso commented on templates/charcoal/admin/widget/quick-form.mustache
> +<style>
J'essaierais p-e de trigger une class css et d'avoir les styles dans un fichier css à la place. Comme c'est fait maintenant, des styles d'autres modal qu'un quick-form pourrais être affecté.

2022-06-02 15:19 UTC, veve40 commented on templates/charcoal/admin/widget/quick-form.mustache
> +<style>
Ouais absolument! Par contre je sais juste pas ou mettre le fichier de style dans l'architecture des templates

2022-06-02 15:22 UTC, veve40 commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function showLanguageSwitch()
Ici j'ai essayé de reprendre la fonctionnalité implementée dans FormSidebarWidget sur l'affichage du lang switcher, mais je ne sais pas si on peut uniformiser le tout ou si il n'y a pas forcement besoin?

2022-06-02 15:24 UTC, veve40 commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function availableLanguages()
J'ai repris le availableLanguages de FormSidebarWidget ici, mais pareil, ce n'est pas uniformisé, les classes FormSidebarWidget et QuickFormWidget n'etant pas en lien.

2022-06-02 15:25 UTC, veve40 commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    protected function sortLanguagesByPriority(array $a, array $b)
De meme pour cette fonction qui est 100% copié/collé de FormSidebarWidget, est ce qu'il faudrait la mettre dans une sorte de Helper?

2022-06-02 15:35 UTC, JoelAlphonso commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function availableLanguages()
On pourrait avoir un HasLangSwitcherTrait maybe ??

2022-06-02 15:35 UTC, mcaskill requested changes

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +     * @return FormWidget Chainable
With future versions of PHP, this will be type-hinted with `self`.

```suggestion
     * @return self
```

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +        return ($this->groupDisplayMode() === self::DISPLAY_MODE_LANG) ? true : false;
In PHP, a comparison expression results in a `boolean`, no need for a ternary expression.

```suggestion
        return ($this->groupDisplayMode() === self::DISPLAY_MODE_LANG);
```

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +        return in_array($this->groupDisplayMode(), $tabbableDisplayModes) ? true : false;
The `in_array()` function results in a `boolean`, no need for a ternary expression.

```suggestion
        return in_array($this->groupDisplayMode(), $tabbableDisplayModes);
```

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +        ];
This should be moved to its own method, `getTabbableDisplayModes()` to allow for customizations.

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +                }
Charcoal's `Translator#translate()` method converts the input value into a `Translation` object and then returns the localized string. This is only useful if your input value could be a `Translation` object or translation array-shape.

When you know that your input value is a string and all you want is a localized string in return, I recommend using Symfony's `Translator#trans()` method instead:

```suggestion
                $trans = 'locale.'.$locale;
                if ($trans === $this->translator()->trans($trans)) {
                    $label = strtoupper($locale);
                } else {
                    $label = $this->translator()->translation($trans);
                }
```

2022-06-02 15:35 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +        return json_encode($this->availableLanguages());
This should provide a more readable output for debugging purposes.

```suggestion
        $options = (JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        if ($this->debug()) {
            $options = ($options | JSON_PRETTY_PRINT);
        }

        return json_encode($this->availableLanguages(), $options);
```

2022-06-02 15:35 UTC, mcaskill commented on templates/charcoal/admin/widget/quick-form.mustache
> +<style>
I second this motion.

2022-06-02 15:35 UTC, mcaskill commented on templates/charcoal/admin/widget/quick-form.mustache
> +    {{> charcoal/admin/l10n/quick-form-languages.js }}
Similar to Joel's [comment](https://github.com/locomotivemtl/charcoal-admin/pull/63/files#r888063771) about externalizing the CSS, the same should be done for the JS.

2022-06-02 15:40 UTC, mcaskill commented on templates/charcoal/admin/widget/quick-form.mustache
> +<style>
> […] je sais juste pas ou mettre le fichier de style dans l'architecture des templates

Yeah, it's a mess architecturally speaking.

Add CSS to this file:

[`/assets/src/styles/charcoal/admin/components/_form-widget.scss`](https://github.com/locomotivemtl/charcoal-admin/blob/0.30.2/assets/src/styles/charcoal/admin/components/_form-widget.scss)

2022-06-02 15:47 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function showLanguageSwitch()
The main difference between this and `FormSidebarWidget` is with the implementation of `ObjectFormWidget::hasL10nFormProperties()`. Your version tests the hydrated model (object type and object ID) whereas `ObjectFormWidget` tests a blank "prototype" model (object type only).

Do you remember why it was overridden?

2022-06-02 15:49 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function availableLanguages()
Yeah, I was thinking we could add a `HasLanguageSwitcherTrait` (or `LanguageSwitchAwareTrait` or `LanguageSwitchableTrait` :p ), was about to say so myself.

2022-06-02 15:50 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    protected function sortLanguagesByPriority(array $a, array $b)
Let's aggregate the discussion in this [thread](https://github.com/locomotivemtl/charcoal-admin/pull/63#discussion_r888111786).

2022-06-02 15:50 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function showLanguageSwitch()
Regarding the centralizing/decoupling of language switching functionnality, let's aggregate the discussion in this [thread](https://github.com/locomotivemtl/charcoal-admin/pull/63#discussion_r888111786).

2022-06-02 18:49 UTC, mcaskill commented
Summary of a chat between @veve40, @mcaskill, @JoelAlphonso:

- [ ] Add support class `Sorter` with method `sortByPriority()`.
  - [ ] Migrate equivalent methods from other classes:
    - `sortLanguagesByPriority()`
    - `sortItemsByPriority()`
    - `sortGroupsByPriority()`
    - `sortActionsByPriority()`
    - Note: This could just be done for `sortLanguagesByPriority()` for now and create another pull request to unify others.
- [ ] Add `HasLanguageSwitcherTrait` and `HasLanguageSwitcherInterface` or maybe as a service class?
  - [ ] Migrate methods `showLanguageSwitch()` from:
    - `QuickFormWidget`
    - `ObjectFormWidget`
    - `FormSidebarWidget`
- [ ] Replace method `hasL10nFormProperties()` on `ObjectFormWidget` with implementation from `QuickFormWidget`.

Proposed structure for `HasLanguageSwitcherTrait`:

<details>
<summary>`HasLanguageSwitcherTrait`</summary>

```php
public function showLanguageSwitch()
{
    if ($this->showLanguageSwitch === null) {
        $this->showLanguageSwitch = $this->resolveShowLanguageSwitch();
    }
    return $this->showLanguageSwitch;
}

abstract protected function resolveShowLanguageSwitch();
```

</details>

<details>
<summary>`QuickFormWidget` / `ObjectFormWidget`</summary>

```php
protected function resolveShowLanguageSwitch()
{
    return $this->hasL10nFormProperties();
}
```

</details>

<details>
<summary>`FormSidebarWidget`</summary>

```php
protected function resolveShowLanguageSwitch()
{
    if ($form) {
        return $form->hasL10nFormProperties();
    }

    return false;
}
```

</details>

2022-06-02 21:33 UTC, mcaskill commented on src/Charcoal/Admin/Ui/HasLanguageSwitcherTrait.php
> +    abstract protected function resolveShowLanguageSwitch();
```suggestion
    /**
     * Resolves whether to display the language switcher or not.
     *
     * @var boolean
     */
    abstract protected function resolveShowLanguageSwitch();
```

2022-06-02 21:34 UTC, mcaskill commented on src/Charcoal/Admin/Ui/HasLanguageSwitcherInterface.php
> + */
```suggestion
/**
 * Language switcher awareness
 */
```

2022-06-03 16:08 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    public function availableLanguages()
Continued in this [thread](https://github.com/locomotivemtl/charcoal-admin/pull/63#issuecomment-1145200158).

2022-06-03 16:09 UTC, mcaskill commented on src/Charcoal/Admin/Widget/QuickFormWidget.php
> +    protected function sortLanguagesByPriority(array $a, array $b)
Continued in this [thread](https://github.com/locomotivemtl/charcoal-admin/pull/63#issuecomment-1145200158).

2022-06-04 00:50 UTC, mcaskill reviewed
Nice work. All that's missing is adding `isDisplayModeLang` and `showLanguageSwitch` to a `QuickFormWidget::widgetDataForJs()` method to wrap the trigger and event lisener that you moved to `quickform.js`.

2022-06-06 18:38 UTC, mcaskill approved these changes

2022-06-06 18:39 UTC, merged